#!/bin/sh

# Create all the symlinks to /bin/busybox
/bin/busybox --install -s

# Mount things needed by this script
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devpts /dev/pts /dev/pts


# Create device nodes
/bin/mknod /dev/null c 1 3
/bin/mknod /dev/tty c 5 0
/sbin/mdev -s


echo "Starting init."
exec /sbin/init


echo "Dropping to a shell with job control. -- 3"
setsid /bin/sh -c 'exec /bin/sh </dev/tty1 >/dev/tty1 2>&1'


echo "Sleeping 6000"
sleep 6000


echo "Shell without job control."
exec /bin/sh
